services:
  - type: web
    name: campusconnect
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: COLLEGE_NAME
        value: "Apex Institute of Engineering & Technology"
      - key: SYSTEM_NAME
        value: "CampusConnect"
